In [3]:
import h5py
import json
import numpy as np

def print_h5_structure(group, indent=0):
    """
    Recursively print the structure of an HDF5 file
    
    Args:
        group: h5py.Group or h5py.File object
        indent: Current indentation level for pretty printing
    """
    # Print group name and attributes
    print(' ' * indent + f"Group: {group.name}")
    if len(group.attrs) > 0:
        print(' ' * (indent + 2) + "Attributes:")
        for attr_name, attr_value in group.attrs.items():
            print(' ' * (indent + 4) + f"{attr_name}: {attr_value}")
    
    # Print datasets in this group
    for name, obj in group.items():
        if isinstance(obj, h5py.Dataset):
            print(' ' * (indent + 2) + f"Dataset: {name}")
            print(' ' * (indent + 4) + f"Shape: {obj.shape}")
            print(' ' * (indent + 4) + f"Type: {obj.dtype}")
            
            # If it's a string dataset that might contain JSON, try to parse it
            if obj.dtype.kind == 'O':
                try:
                    data = obj[()]
                    if isinstance(data, str):
                        parsed = json.loads(data)
                        print(' ' * (indent + 4) + f"Content (JSON parsed): {parsed}")
                    else:
                        print(' ' * (indent + 4) + f"Content: {data}")
                except:
                    print(' ' * (indent + 4) + f"Content: {obj[()]}")
        else:
            # Recursively print subgroups
            print_h5_structure(obj, indent + 2)

def explore_h5(file_path):
    """
    Explore HDF5 file structure
    
    Args:
        file_path: Path to the HDF5 file
    """
    try:
        with h5py.File(file_path, 'r') as f:
            print("=== HDF5 File Structure ===")
            print_h5_structure(f)
    except Exception as e:
        print(f"Error opening file: {e}")

# Example usage:
# Replace 'your_file.h5' with your actual HDF5 file path
explore_h5('geopomdp_1run_minimal.h5')

=== HDF5 File Structure ===
Group: /
  Group: /realization1
    Group: /realization1/static
      Dataset: econ_params
        Shape: ()
        Type: int64
      Dataset: eng_params
        Shape: ()
        Type: int64
      Dataset: fault_id
        Shape: (326, 120, 162)
        Type: int64
      Dataset: geo_params
        Shape: ()
        Type: int64
      Dataset: is_active
        Shape: (326, 120, 162)
        Type: uint8
      Dataset: permx
        Shape: (326, 120, 162)
        Type: float64
      Dataset: permy
        Shape: (326, 120, 162)
        Type: float64
      Dataset: permz
        Shape: (326, 120, 162)
        Type: float64
      Dataset: porosity
        Shape: (326, 120, 162)
        Type: float64
      Dataset: x
        Shape: (326, 120, 162)
        Type: float64
      Dataset: y
        Shape: (326, 120, 162)
        Type: float64
      Dataset: z
        Shape: (326, 120, 162)
        Type: float64
    Group: /realization1/trajectories
      Group: /rea

In [5]:
explore_h5("BC_EN_120.h5")

=== HDF5 File Structure ===
Group: /
  Dataset: dataset1
    Shape: (100, 50)
    Type: float64
  Group: /my_experiments
    Dataset: exp_A_results
      Shape: (5,)
      Type: int64


In [6]:
import h5py

# Open the HDF5 file
with h5py.File('geopomdp_1run_minimal.h5', 'r') as f:
    # Access the permx dataset
    permx = f['realization1/static/permx'][:]
    
    # Print some information about the dataset
    print(f"Shape of permx dataset: {permx.shape}")
    print(f"Data type: {permx.dtype}")
    
    # If you want to see the first few values
    print("First few values:")
    print(permx[:5])  # Adjust the number as needed

Shape of permx dataset: (326, 120, 162)
Data type: float64
First few values:
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
